<h1>Lista de Usuários</h1>

<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="btn btn-success" href="/usuarios/cadastro"> + Adicionar usuário</a>
  </li>
</ul>

<table class="table table-striped table-hover mt-3">
    <thead class="table-dark">
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Criado em</th>
            <th>Ultimo login</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($dados as $cada) {
                $ultimoLogin = $cada['updated_at'] ?? '<span class="badge bg-danger">Nunca logou</span>';

                echo "<tr>
                    <td>{$cada['nome']}</td>
                    <td>{$cada['email']}</td>
                    <td>{$cada['created_at']}</td>
                    <td>{$ultimoLogin}</td>
                    <td>
                        <a href='/usuarios/excluir?id={$cada['id']}' class='btn btn-outline-danger'>Excluir</a>
                        <a href='/usuarios/editar?id={$cada['id']}' class='btn btn-outline-warning'>Editar</a>
                    </td>
                </tr>";
            }
        ?>
    </tbody>
</table>