<h2> Adicionar produto </h2>
<form action="" method="post">
  <div class="mb-3">
    <label for="label_descricao" class=""> Descrição </label>
    <input type="text" class="form-control" id="label_descricao" name="descricao" placeholder="" required>
  </div>
  <div class="mb-3">
    <label for="label_valor" class=""> Valor </label>
    <input type="decimal" class="form-control" id="label_valor" name="valor" placeholder="" step="0.01" min="0" required>
    <!--<input type="text" class="form-control" id="label_valor" name="valor" placeholder="" required>-->
  </div>
  <button class="btn btn-dark" type="submit"> Adicionar </button>
</form>