        </section>
        <footer>
            <div class="container">
                <p>
                    <a class="MarkRyk" href="https://github.com/markryk" target="_blank"><ion-icon name="logo-github" size="large"></ion-icon> Mark Ryk </a>
                </p>
            </div>
        </footer>

        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    </body>
</html>