<h2> Adicionar restaurante </h2>
<form action="" method="post">
  <div class="mb-3">
    <label for="label_nome" class=""> Nome </label>
    <input type="text" class="form-control" id="label_nome" name="nome" placeholder="" required>
  </div>
  <div class="mb-3">
    <label for="label_endereco" class=""> Endereço </label>
    <input type="text" class="form-control" id="label_endereco" name="endereco" placeholder="" required>
  </div>
  
  <a href='/restaurantes' class='btn btn-outline-dark'> Voltar </a>
  <button class="btn btn-primary" type="submit"> Adicionar </button>
</form>