<h1> Editar restaurante [ <?=$dados['nome'];?> ] </h1>

<form method="post" action="">
    <label for="nome">Nome</label>
    <input id="nome" value="<?php echo $dados['nome'] ?>" class="form-control mb-3" name="nome">

    <label for="endereco">Endereço</label>
    <input id="endereco" value="<?=$dados['endereco'] ?>" class="form-control mb-3" name="endereco">

    <!--<button class="btn btn-primary">PRONTO</button>-->
    <a href='/restaurantes' class='btn btn-outline-dark'> Voltar </a>
    <button class="btn btn-primary"> OK </button>
</form>